"""change tablename BankTransaction to Transaction

Revision ID: 3293e3553a48
Revises: 9b88bba18df0
Create Date: 2020-08-22 18:27:04.414866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3293e3553a48'
down_revision = '9b88bba18df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.drop_index('account_transaction_id')

    op.drop_table('bank_transaction')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('account_id_transaction_id', ['account_id', 'transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('account_id_transaction_id')

    op.create_table('bank_transaction',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=250), nullable=True),
    sa.Column('transaction_date', sa.DATE(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=250), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='fk_bank_transaction_category_id_category'),
    sa.PrimaryKeyConstraint('id', name='pk_bank_transaction')
    )
    with op.batch_alter_table('bank_transaction', schema=None) as batch_op:
        batch_op.create_index('account_transaction_id', ['account_id', 'transaction_id'], unique=False)

    # ### end Alembic commands ###
