"""initial commit

Revision ID: 365aec0ef12f
Revises: 
Create Date: 2020-08-13 13:29:15.912091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365aec0ef12f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.String(length=250), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('account_transaction_id', 'bank_transaction', ['account_id', 'transaction_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index('account_transaction_id', table_name='bank_transaction')
    op.drop_table('bank_transaction')
    # ### end Alembic commands ###
